project:
  type: website
  output-dir: docs

website:
  title: "Jim Grange"
  navbar:
    background: skyblue
    foreground: light
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: posts.qmd
        text: Blog
  # tools:
  #     - icon: twitter
  #       href: https://twitter.com
  #     - icon: github
  #       menu:
  #         - text: Source Code
  #           url:  https://github.com/JimGrange/jimgrange.github.io
  #         - text: Report a Bug
  #           url:  https://github.com/JimGrange/jimgrange.github.io/issues

format:
  html:
    theme: cosmo
    css: 
      - styles.css
      - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css
    toc: true

editor: visual

