project:
  type: website
  output-dir: docs

website:
  title: "Jim Grange"
  navbar:
    background: skyblue
    foreground: light
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: posts.qmd
        text: Blog
      - href: cv/Grange_cv.pdf
        text: CV
      - icon: github
        href: https://github.com/JimGrange/JimGrange.github.io
      - icon: twitter
        href: https://twitter.com/JimGrange
  page-footer: 
    background: light
    left: 
      - "CC BY 4.0"
    right: 
      - icon: github
        href: https://github.com/JimGrange
      - icon: twitter
        href: https://twitter.com/JimGrange
  twitter-card: true
  google-analytics: 
    tracking-id: "G-13NEC42TVF"
    anonymize-ip: true
format:
  html:
    page-layout: full
    theme: 
      # light: flatly
      # dark: darkly
      - green_theme.scss
    css: 
      - styles.css
      - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css
    toc: true

editor: visual

